package com.goaltracker.api;

/**
 * Public DTO for a tag attached to a goal. No internal model classes referenced.
 */
public class TagView
{
	/** Stable tag entity id (UUID). Mission 19. */
	public String id;
	public String label;
	/** Category name as a string. One of: BOSS, RAID, CLUE, MINIGAME, SKILLING, OTHER. */
	public String category;
	/** Current tag pill color — user override if set, else the category default. */
	public int colorRgb;
	/** Category default color, even when an override is set. */
	public int defaultColorRgb;
	/** True when {@link #colorRgb} is a user override. */
	public boolean colorOverridden;
	/** True if this tag was auto-generated by the plugin (system tag). Mission 19. */
	public boolean system;
	/** Icon resource key (Mission 21). null means "render as colored pill".
	 *  See Tag.iconKey javadoc for the resolution rules. */
	public String iconKey;

	public TagView() {}

	public TagView(String label, String category, int colorRgb)
	{
		this.label = label;
		this.category = category;
		this.colorRgb = colorRgb;
		this.defaultColorRgb = colorRgb;
		this.colorOverridden = false;
	}

	public TagView(String label, String category, int colorRgb, int defaultColorRgb, boolean overridden)
	{
		this.label = label;
		this.category = category;
		this.colorRgb = colorRgb;
		this.defaultColorRgb = defaultColorRgb;
		this.colorOverridden = overridden;
	}
}
