package com.goaltracker.model;

import java.util.UUID;
import lombok.Builder;
import lombok.Data;

/**
 * A first-class tag entity. Replaces the per-goal embedded {@code ItemTag}
 * model from Mission 17 and earlier.
 *
 * <p>Tags have stable IDs and live in their own collection on
 * {@link com.goaltracker.persistence.GoalStore}. Goals reference tags by id
 * via {@code Goal.tagIds}, so renaming or recoloring a tag at the entity
 * level propagates instantly to every goal using it.
 *
 * <p>The {@link #system} flag distinguishes tags created by the plugin
 * (auto-generated on goal creation, e.g. Boss/Raid/Tier/Slayer on combat
 * achievements) from tags created by the user. The flag drives the edit
 * permissions:
 * <ul>
 *   <li><b>User tags</b> (any category): rename ✓ recolor ✓ delete ✓</li>
 *   <li><b>System tags</b>, SKILLING category: rename ✗ recolor ✗ delete ✗ (skill icons)</li>
 *   <li><b>System tags</b>, other categories: rename ✗ recolor ✓ delete ✗</li>
 * </ul>
 *
 * <p>The {@code colorRgb} field is a packed 0xRRGGBB user override; -1
 * means "use the category default color from {@link TagCategory#getColor()}".
 * Per-goal color overrides do not exist — recoloring a tag affects every
 * goal that references it.
 */
@Data
@Builder
public class Tag
{
	@Builder.Default
	private String id = UUID.randomUUID().toString();

	private String label;
	private TagCategory category;

	/**
	 * Per-tag color override, packed as 0xRRGGBB. -1 means "use the category color".
	 *
	 * <p>Mission 20 split tag color responsibility by category:
	 * <ul>
	 *   <li>OTHER tags: this field is the source of truth. Each Other tag can
	 *       carry its own color independent of every other Other tag.</li>
	 *   <li>BOSS / RAID / CLUE / MINIGAME tags: this field is IGNORED. Color
	 *       comes from the category-level override on GoalStore.categoryColors,
	 *       so all tags in the category share one color.</li>
	 *   <li>SKILLING tags: rendered as skill icons, color is irrelevant.</li>
	 * </ul>
	 */
	@Builder.Default
	private int colorRgb = -1;

	/**
	 * True if this tag was auto-generated by the plugin (e.g. attached to a
	 * combat achievement goal at creation time). False for user-created tags.
	 * System tags cannot be renamed or deleted.
	 */
	@Builder.Default
	private boolean system = false;

	/**
	 * Icon resource key (Mission 21). null means "no icon, render as a colored pill".
	 *
	 * <p>Resolver: if the key matches a {@link net.runelite.api.Skill} enum
	 * name (case-insensitive), the renderer pulls the icon from
	 * {@code SkillIconManager.getSkillImage(skill)}. Otherwise it tries to
	 * load {@code /icons/<iconKey>.png} as a bundled classpath resource.
	 * If both lookups fail, the tag falls back to color rendering.
	 *
	 * <p>When an icon resolves successfully, it entirely replaces the colored
	 * pill — color and icon are mutually exclusive at render time.
	 */
	private String iconKey;
}
