package com.goaltracker.model;

import java.util.UUID;
import lombok.Builder;
import lombok.Data;

/**
 * A first-class tag entity. Replaces the per-goal embedded {@code ItemTag}
 * model from Mission 17 and earlier.
 *
 * <p>Tags have stable IDs and live in their own collection on
 * {@link com.goaltracker.persistence.GoalStore}. Goals reference tags by id
 * via {@code Goal.tagIds}, so renaming or recoloring a tag at the entity
 * level propagates instantly to every goal using it.
 *
 * <p>The {@link #system} flag distinguishes tags created by the plugin
 * (auto-generated on goal creation, e.g. Boss/Raid/Tier/Slayer on combat
 * achievements) from tags created by the user. The flag drives the edit
 * permissions:
 * <ul>
 *   <li><b>User tags</b> (any category): rename ✓ recolor ✓ delete ✓</li>
 *   <li><b>System tags</b>, SKILLING category: rename ✗ recolor ✗ delete ✗ (skill icons)</li>
 *   <li><b>System tags</b>, other categories: rename ✗ recolor ✓ delete ✗</li>
 * </ul>
 *
 * <p>The {@code colorRgb} field is a packed 0xRRGGBB user override; -1
 * means "use the category default color from {@link TagCategory#getColor()}".
 * Per-goal color overrides do not exist — recoloring a tag affects every
 * goal that references it.
 */
@Data
@Builder
public class Tag
{
	@Builder.Default
	private String id = UUID.randomUUID().toString();

	private String label;
	private TagCategory category;

	/**
	 * Packed 0xRRGGBB color override; -1 means "use the category default".
	 * Affects every goal that references this tag (no per-goal layer).
	 */
	@Builder.Default
	private int colorRgb = -1;

	/**
	 * True if this tag was auto-generated by the plugin (e.g. attached to a
	 * combat achievement goal at creation time). False for user-created tags.
	 * System tags cannot be renamed or deleted; only the color is editable
	 * (and even that is locked for SKILLING-category system tags, which
	 * render as skill icons).
	 */
	@Builder.Default
	private boolean system = false;
}
